### ISSUE TITLE
"The Chicago Debate" (1929)

### ISSUE THREAD

**Issue by pbinkley** [nealcaren/fightordie#10]
Du Bois, W.E.B. 1929. "The Chicago Debate." *The Crisis*. 36(5):167.

Proposed Section: Race science
 
[the-chicago-debate.md](https://github.com/nealcaren/fightordie/files/10009082/the-chicago-debate.md)
[167.pdf](https://github.com/nealcaren/fightordie/files/10009039/167.pdf)

**Comment by nealcaren** [comment]
Great! I added [two notes on this one](https://www.dareyoufight.org/Volumes/36/05/chicago_debate.html).
