### ISSUE TITLE
Missionaries (1929)

### ISSUE THREAD

**Issue by pbinkley** [nealcaren/fightordie#11]
Du Bois, W.E.B. 1929. "Missionaries." The Crisis. 36(5):168.

The beginning of paragraph two appears to be a typo: "One of 158" should be "Out of 158". I've left the text as printed.

Proposed section: Segregation

[missionaries.md](https://github.com/nealcaren/fightordie/files/10009178/missionaries.md)
[168.pdf](https://github.com/nealcaren/fightordie/files/10009179/168.pdf)

**Comment by nealcaren** [comment]
Awesome. Put it in a [new religion section](https://www.dareyoufight.org/Sections/religion.html). 

Following Herbert Aptheker (his literary executor), I've been leaving the text as printed, except for small typographical errors ("teh" -> "the").
