### ISSUE TITLE
Optimism (1929)

### ISSUE THREAD

**Issue by pbinkley** [nealcaren/fightordie#12]
Du Bois, W.E.B. 1929. "Optimism." The Crisis. 36(5):168.

Proposed section: Education

[optimism.md](https://github.com/nealcaren/fightordie/files/10009193/optimism.md)
[168.pdf](https://github.com/nealcaren/fightordie/files/10009187/168.pdf)

**Comment by nealcaren** [comment]
Great! In [education for now](https://www.dareyoufight.org/Volumes/36/05/optimism.html), but might fit better elsewhere as that section develops.
