### ISSUE TITLE
"George Washington and Black Folk"

### ISSUE THREAD

**Issue by yuanweij** [nealcaren/fightordie#14]
Du Bois, W.E.B. 1932. “George Washington and Black Folk” The Crisis. 39(4): 121-124.

Proposed section: The Arts?

[George Washington and Black Folk.pdf](https://github.com/nealcaren/fightordie/files/12316765/George.Washington.and.Black.Folk.pdf)
[George Washington and Black Folk.md](https://github.com/nealcaren/fightordie/files/12316837/George.Washington.and.Black.Folk.md)

Note: This is a pageant manuscript. It needs further formatting.

The OCR initially failed to separate the columns here and there. It improved after I provided the beginning and ending sentences of each column. Still, the best solution might be to perform OCR on separate PDFs for each column.

**Comment by nealcaren** [comment]
Thanks. I'll have some folks work on in next weeks to see what we can do.
