### ISSUE TITLE
"The Possibility of Democracy in America"

### ISSUE THREAD

**Issue by yuanweij** [nealcaren/fightordie#15]
*Citation:* Du Bois, W.E.B. 1928. "The Possibility of Democracy in America.” *The Crisis*. 35(10):336, 353&ndash;355.

Proposed Section: Disenfranchisement
[possiblility_of_democracy.md](https://github.com/nealcaren/fightordie/files/12352149/possiblility_of_democracy.md)
[possiblility_of_democracy.pdf](https://github.com/nealcaren/fightordie/files/12352150/possiblility_of_democracy.pdf)

Figure: [disfranchisement_in_the_south.png](https://www.dropbox.com/scl/fi/vbtcaar23c0cldkm9lnf1/disfranchisement_in_the_south.png?rlkey=nyj8jlgquvn77g8om93kb9mku&dl=0)

Note:
1. "For several years after the World War I used to talk concerning the results of the War, and to say that notwithstanding the slaughter and the upheaval that always accompany war we were going to have in the world an extension of democracy as a result of the fighting."— See Du Bois, W.E.B. 1919. "Returning Soldiers." *The Crisis*. 18(1):12&ndash;13.
2. "In the September <span style="font-variant:small-caps;">Crisis</span> I showed how, where and why American Negroes were not free to vote." — See Du Bois, W.E.B. 1928. "The Possibility of Democracy." *The Crisis*. 35(9):296&ndash;296, 314&ndash;315.

Super interesting piece!

**Comment by nealcaren** [comment]
Awesome! Added.

**Comment by yuanweij** [comment]
The figure, [disfranchisement_in_the_south.png](https://www.dropbox.com/scl/fi/vbtcaar23c0cldkm9lnf1/disfranchisement_in_the_south.png?rlkey=nyj8jlgquvn77g8om93kb9mku&dl=0), didn't show up on the [webpage](https://www.dareyoufight.org/Volumes/35/10/possible_democracy.html), though. In the .md file, I called it from ../../../Images/disfranchisement_in_the_south.jpg, though I could not add files to that folder.
