### ISSUE TITLE
Credit, 1915, Volume 10(1):31

### ISSUE THREAD

**Issue by milamascenik** [nealcaren/fightordie#5]
[The Crisis 1915-05_ Vol 10 Iss 1 Page 31.pdf](https://github.com/nealcaren/fightordie/files/9787518/The.Crisis.1915-05_.Vol.10.Iss.1.Page.31.pdf)
[Credit (1915) (1).md](https://github.com/nealcaren/fightordie/files/9787557/Credit.1915.1.md)

**Comment by nealcaren** [comment]
Thanks for your first submission! I removed the text below the citation and [added it](http://www.dareyoufight.org/Volumes/10/01/credit.html) to the [NAACP section](http://www.dareyoufight.org/Sections/NAACP.html).
