### ISSUE TITLE
Submission - "Peace"

### ISSUE THREAD

**Issue by zoeturner23** [nealcaren/fightordie#6]
Du Bois, W.E.B. 1915. “Peace” The Crisis. 10(1): 128.

proposed section: [Colonization](http://www.dareyoufight.org/Sections/colonialization.html)

[peace.md](https://github.com/nealcaren/fightordie/files/9811547/peace.md)

[peace.pdf](https://github.com/nealcaren/fightordie/files/9811916/sim_crisis_1915-05_10_1.pdf.page.28.pdf)

**Comment by nealcaren** [comment]
[Published](http://www.dareyoufight.org/Volumes/10/01/peace.html)!
