### ISSUE TITLE
"The Republicans"

### ISSUE THREAD

**Issue by zoeturner23** [nealcaren/fightordie#7]
Du Bois, W.E.B. 1915. “The Republicans” The Crisis. 10(1): 128.

Proposed Section: [Voting and Parties](http://www.dareyoufight.org/Sections/electoral.html) 

[therepublicans.md](https://github.com/nealcaren/fightordie/files/9812127/therepublicans.md)

[therepublcians.pdf](https://github.com/nealcaren/fightordie/files/9812132/sim_crisis_1915-05_10_1.pdf.page.28.pdf)

**Comment by nealcaren** [comment]
Looks great! I just added a "_" to the file name between the words and the year to the first line.  [Published](http://www.dareyoufight.org/Volumes/10/01/the_republicans.html)
