### ISSUE TITLE
"The Fourteenth Amendment"

### ISSUE THREAD

**Issue by zoeturner23** [nealcaren/fightordie#8]
Du Bois, W.E.B. 1915. “The Fourteenth Amendment” The Crisis. 10(1): 128.

Proposed Section: [Racism and Discrimination](https://www.dareyoufight.org/Sections/racism.html)

[TheFourteenthAmendment.md](https://github.com/nealcaren/fightordie/files/9880116/TheFourteenthAmendment.md)

[TheFourteenthAmendment.pdf](https://github.com/nealcaren/fightordie/files/9880121/sim_crisis_1915-05_10_1.pdf.page.28.pdf)

**Comment by nealcaren** [comment]
Great! [Added](https://www.dareyoufight.org/Volumes/10/01/fourteenth_amendment.html).
