### ISSUE TITLE
Hoover and the South, vol. 36 1929 May p.167

### ISSUE THREAD

**Issue by pbinkley** [nealcaren/fightordie#9]
[hoover_and_the_south.md](https://github.com/nealcaren/fightordie/files/9999961/hoover_and_the_south.md)

Not sure about a section: Republicans? South? Southern politics?

**Comment by nealcaren** [comment]
Great! Added the metadata up top and [posted](https://www.dareyoufight.org/Volumes/36/05/hoover_and_the_south.html) in Voting for now.
